[channel]
generator = utipod
	xmlbase = http://utubeipod.xyz:8080/UC7_X0WkMtkWzaVUKF-PRBNQ
title = "Hyperledger Foundation"
link = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
description = "The Open Source, Global Ecosystem for Enterprise Grade Blockchain Technologies "

[channel "image"]
url = https://yt3.googleusercontent.com/Zl6Lkbdm-lu1fDZUqBMH2SjmPYJkWnytP93DaszjCojzJAxvCW3lIv_D3VlRN7Je2u9GUS2y=s0

