[item]
guid = 17sLDiLzGUU
title = "Largest NFT deployment with IPWE with @ #consensus23 #hyperledgercacti"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=17sLDiLzGUU
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/17sLDiLzGUU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/17sLDiLzGUU/hq2.jpg

