[item]
guid = 3tOjwSUetFA
title = "Alex Migitko of GameCredits on Hyperledger"
description = "Alex Migitko is the COO of GameCredits and a member of Hyperledger. As a blockchain company, GameCredits joined Hyperledger to better understand how to build private, permissioned blockchains. They're currently building with Hyperledger Fabric.\n\n----\nHyperledger – Open Source Blockchain Technologies\n\nHyperledger is an open source community focused on developing a suite of stable frameworks, tools and libraries for enterprise-grade blockchain deployments.\nIt serves as a neutral home for various distributed ledger frameworks including Hyperledger Besu, Fabric, Sawtooth, Indy, as well as tools like Hyperledger Avalon, Cactus and libraries like Hyperledger Aries, Ursa. Learn more about Hyperledger projects: https://www.hyperledger.org/use\n\nCase Studies: https://www.hyperledger.org/learn/case-studies\nTraining & Certification: https://www.hyperledger.org/learn/training\nTutorials: https://www.hyperledger.org/use/tutorials\nWebinars: https://www.hyperledger.org/learn/webinars\nEvents: https://www.hyperledger.org/events \nVendor Directory: https://www.hyperledger.org/use/vendor-directory \n\nSubscribe to the Hyperledger Newsletter: https://www.hyperledger.org/newsletter\n\nFollow-us on Twitter @Hyperledger \n\nLearn about Hyperledger Membership: https://www.hyperledger.org/about/join\n\n#Hyperledger #HyperledgerCommunity #Blockchain"
author = Hyperledger Foundation
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=3tOjwSUetFA
category = "People & Blogs"
pubdate = Tue, 13 Feb 2018 00:00:00 -0000
enclosure = v/3tOjwSUetFA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/3tOjwSUetFA/maxresdefault.webp

