[item]
guid = 44Y8GB9R2KY
title = "Alastria ‘public and permissions networks’ @consensus23"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=44Y8GB9R2KY
category = "Education"
author = Hyperledger Foundation
pubdate = Thu, 27 Apr 2023 00:00:00 -0000
enclosure = v/44Y8GB9R2KY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/44Y8GB9R2KY/hq2.jpg

