[item]
guid = A-ItFR5Y5Vg
title = "IntellectEU presenting at our Consensus23 booth 312 come visit!"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=A-ItFR5Y5Vg
category = "Education"
author = Hyperledger Foundation
pubdate = Thu, 27 Apr 2023 00:00:00 -0000
enclosure = v/A-ItFR5Y5Vg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/A-ItFR5Y5Vg/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYTiBiKGUwDw==&rs=AOn4CLB75gfKWnPd2El14EdL6ZYWT7Dwxg

