[item]
description = "Hyperledger Global Forum will bring together 700+ attendees in Dublin Ireland on September 12-13th. \n\nThis is short video with Hyperledger Foundation Executive Director, Daniela Barbosa is an open invitation to all community members who participate in our Special Interest Groups (SIGs) to submit a talk during our Call For Proposals (CFP) . Details here: \nhttps://events.linuxfoundation.org/hyperledger-global-forum/\n\nTo learn more about our open community SIGs in #CapitalMarkets, #Climate #Healthcare #Media #Gaming #Governance #PublicSector #SupplyChain #TradeFinance #Telecom and more please see: https://wiki.hyperledger.org/display/HYP/Special+Interest+Groups"
category = "Education"
title = "Invitation Hyperledger Global Forum 2022: Hyperledger Special Interest Groups (SIGs)"
pubdate = Fri, 01 Apr 2022 00:00:00 -0000
enclosure = v/BHRXJEkewYk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/BHRXJEkewYk/maxresdefault.webp

