[item]
guid = e24-RpY7f_k
title = "ConsenSys Mesh on zkEVM and Firefly for Enterprise"
description = "----\nMark Rymsza discussing decentralized business automation as a service: Leveraging zkEVM and Hypeledger Firefly for Enterprise business, and the challenges with digital transformation and data sharing.\n\nPresented by the Enterprise ZK R&D team from ConsenSyS Mesh @Hyperledger Consensus 2023 booth.\n\n✦\nDecentralized business automation for Enterprise using ZK Roll-Ups on Ethereum\n00:00\n✦\nThe increasing use of IoT devices in business processes is leading to a lack of trust and increasing costs for enterprises.\n03:43\n✦\nZero trust network architecture is crucial for secure data exchange.\n07:22\n✦\nZero knowledge cryptography enables granular access control enforcement\n10:36\n✦\nZK EVM allows private execution of smart contracts for complex end-to-end digital services.\n14:02\n✦\nFirefly enables a trustless ZK internet for Enterprises\n17:00\n✦\nDeveloping two pilot products for end-to-end services in Telecom using ZK EVM as a service and DAO as a service.\n00:03\n✦\nDecentralized business automation is critical for future business success.\n\n22:57"
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=e24-RpY7f_k
category = "Education"
author = Hyperledger Foundation
pubdate = Mon, 08 May 2023 00:00:00 -0000
enclosure = v/e24-RpY7f_k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/e24-RpY7f_k/maxresdefault.jpg

