[item]
guid = E4Jl8ME7NC8
title = "Hyperledger Sweden Meetup - April 2, 2020"
description = "A virtual meetup hosted by Hyperledger Sweden featuring Raimund Mollner from AFRY and Marta Piekarska from the Linux Foundation.  \n\nMore details about this event are at: \nhttps://www.meetup.com/Hyperledger-Sweden/events/269677385/\n\n----\nHyperledger – Open Source Blockchain Technologies\n\nHyperledger is an open source community focused on developing a suite of stable frameworks, tools and libraries for enterprise-grade blockchain deployments.\nIt serves as a neutral home for various distributed ledger frameworks including Hyperledger Besu, Fabric, Sawtooth, Indy, as well as tools like Hyperledger Avalon, Cactus and libraries like Hyperledger Aries, Ursa. Learn more about Hyperledger projects: https://www.hyperledger.org/use\n\nCase Studies: https://www.hyperledger.org/learn/case-studies\nTraining & Certification: https://www.hyperledger.org/learn/training\nTutorials: https://www.hyperledger.org/use/tutorials\nWebinars: https://www.hyperledger.org/learn/webinars\nEvents: https://www.hyperledger.org/events \nVendor Directory: https://www.hyperledger.org/use/vendor-directory \n\nSubscribe to the Hyperledger Newsletter: https://www.hyperledger.org/newsletter\n\nFollow-us on Twitter @Hyperledger \n\nLearn about Hyperledger Membership: https://www.hyperledger.org/about/join\n\n#Hyperledger #HyperledgerMeetups #Blockchain"
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=E4Jl8ME7NC8
category = "Science & Technology"
author = Hyperledger Foundation
pubdate = Mon, 06 Apr 2020 00:00:00 -0000
enclosure = v/E4Jl8ME7NC8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/E4Jl8ME7NC8/maxresdefault.webp

