[item]
guid = F3sLeWvC3Sw
title = "Instnt kicking off day 2 @consensus23"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=F3sLeWvC3Sw
category = "Education"
author = Hyperledger Foundation
pubdate = Thu, 27 Apr 2023 00:00:00 -0000
enclosure = v/F3sLeWvC3Sw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/F3sLeWvC3Sw/hq2.jpg

