[item]
guid = gmv3svU1qtc
title = "ZEEVE @consensus23 presenting an intro in the enterprise block chain tools"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=gmv3svU1qtc
category = "Education"
author = Hyperledger Foundation
pubdate = Thu, 27 Apr 2023 00:00:00 -0000
enclosure = v/gmv3svU1qtc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/gmv3svU1qtc/hq2.jpg

