[item]
guid = I51e3Z_VD1c
title = "io.builders on ownership diving NFT fan engagement and their platform Wuonka"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=I51e3Z_VD1c
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/I51e3Z_VD1c.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/I51e3Z_VD1c/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYZSBaKFowDw==&rs=AOn4CLDtNkLR2jmPUAboZ16u4qfJuUh3Cg

