[item]
guid = LAPFEvTysy0
title = "Kaleido and Sophia Lopez person eng at our @consensus23 booth 🚀"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=LAPFEvTysy0
category = "Education"
author = Hyperledger Foundation
pubdate = Thu, 27 Apr 2023 00:00:00 -0000
enclosure = v/LAPFEvTysy0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/LAPFEvTysy0/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYwCgALgA4oCDAgAEAEYRCBjKGUwDw==&rs=AOn4CLCopGPb_Qf0bU0td0MpMpll0qBezA

