[item]
guid = lU0FPiUJXyI
title = "Deloitte @consensus23 #HyperledgerFirefly"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=lU0FPiUJXyI
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/lU0FPiUJXyI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/lU0FPiUJXyI/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLAT1OQ4T5FSYKFIvU7j4RADwez5rw

