[item]
guid = NFd3BgCmnmY
title = "International Development Bank #consensus23 #Hyperledgerbesu"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=NFd3BgCmnmY
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/NFd3BgCmnmY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/NFd3BgCmnmY/hq2.jpg

