[item]
description = "----\nJoin us in Dublin, Ireland Sept 12-14th, where we are back in person for the biggest annual gathering of the global Hyperledger community. 🍀\n\nRead our highlights and some of the talks and themes are community will be covering:\nClimate\nCBDCs\nDigital Identity\nEnterprise Blockchain\nHands-on Workshops\nand More! \n\nhttps://hyperledger.org/blog/2022/07/26/whats-on-the-agenda-at-hyperledger-global-forum-2022"
category = "Education"
title = "Hyperledger Global Forum Dublin, Ireland 2022"
pubdate = Tue, 16 Aug 2022 00:00:00 -0000
enclosure = v/PoSJvX-23j0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/PoSJvX-23j0/maxresdefault.webp

