[item]
guid = ql9XniY3Sn4
title = "io.builders @consensus23 discussing their unique platforms built on Hyperledger"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=ql9XniY3Sn4
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/ql9XniY3Sn4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ql9XniY3Sn4/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYwCgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLAI1_J9USJvJM6pw8Bsr_i-U-x6lg

