[item]
guid = rCuHJvQLBh0
title = "io.builders kicking off presentations today @consensus23"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=rCuHJvQLBh0
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/rCuHJvQLBh0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/rCuHJvQLBh0/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYwCgALgA4oCDAgAEAEYZSBaKFswDw==&rs=AOn4CLDVk3i3bHDLRWh3isopHwp6_6DAGw

