[item]
guid = RM1hqyWkSqE
title = "Casper Labs introduction at #consensus23"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=RM1hqyWkSqE
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/RM1hqyWkSqE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/RM1hqyWkSqE/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4Ac4FgAKACooCDAgAEAEYUCBlKGUwDw==&rs=AOn4CLDo_MAlcSGei8OuaDV_H0s_djn9yA

