[item]
guid = x3wbfXtIcS4
title = "Fantastic io.builders Wuonka platform NFT use cases"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=x3wbfXtIcS4
category = "Education"
author = Hyperledger Foundation
pubdate = Fri, 28 Apr 2023 00:00:00 -0000
enclosure = v/x3wbfXtIcS4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/x3wbfXtIcS4/hq2.jpg

