[item]
guid = ydSG_cKEidU
title = "Alastria @consensus2023 booth"
description = ""
source = https://www.youtube.com/channel/UC7_X0WkMtkWzaVUKF-PRBNQ
link = https://www.youtube.com/watch?v=ydSG_cKEidU
category = "Education"
author = Hyperledger Foundation
pubdate = Thu, 27 Apr 2023 00:00:00 -0000
enclosure = v/ydSG_cKEidU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ydSG_cKEidU/sd2.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AYwCgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLCO5BFElBPNQ88KFdK4rxI_lFvNoA

